name: tarot
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:

  avatar_glow:
  bordered_text: ^2.0.0
  cached_network_image:
  carousel_slider:
  cupertino_icons:

  flutter:
    sdk: flutter

  flutter_launcher_icons:
  flutter_native_splash:
  flutter_polyline_points:
  flutter_riverpod: ^2.5.1
  font_awesome_flutter:

  freezed_annotation: ^2.4.4

  get:
  google_fonts: ^3.0.1
  google_maps_flutter:

  hooks_riverpod: ^2.5.2

  http: ^0.13.6
  intl: ^0.19.0

  json_annotation: ^4.9.0

  riverpod_annotation: ^2.3.5
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.5
  uuid:

dev_dependencies:

  build_runner: ^2.4.9

  flutter_lints:

  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:

  uses-material-design: true

  assets:
    - assets/image/

flutter_native_splash:
  image: "assets/image/tarotcard.png"
  color: "2e2e2e"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/launchericon.JPG"

  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/image/launchericon.JPG"
